# Generated by Django 6.0.3 on 2026-03-27 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        help_text="The name of the category in Russian.",
                        max_length=255,
                        unique=True,
                        verbose_name="Russian name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        help_text="The name of the category in English.",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="English name",
                    ),
                ),
                (
                    "name_ch",
                    models.CharField(
                        blank=True,
                        help_text="The name of the category in Chinese.",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Chinese name",
                    ),
                ),
                (
                    "order_id",
                    models.SmallIntegerField(blank=True, default=10, null=True),
                ),
            ],
            options={
                "verbose_name": "Menu section",
                "verbose_name_plural": "Menu sections",
                "ordering": ("name_ru", "order_id"),
            },
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                ("is_vegan", models.BooleanField(default=False, verbose_name="Vegan")),
                (
                    "is_special",
                    models.BooleanField(default=False, verbose_name="Special offer"),
                ),
                ("code", models.IntegerField(verbose_name="Supplier code")),
                (
                    "internal_code",
                    models.IntegerField(
                        blank=True, null=True, unique=True, verbose_name="App code"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, verbose_name="Russian name"),
                ),
                (
                    "description_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Russian description",
                    ),
                ),
                (
                    "description_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="English description",
                    ),
                ),
                (
                    "description_ch",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Chinese description",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Cost"
                    ),
                ),
                (
                    "is_publish",
                    models.BooleanField(default=True, verbose_name="Published"),
                ),
                (
                    "additional",
                    models.ManyToManyField(
                        blank=True,
                        related_name="additional_from",
                        to="menu.food",
                        verbose_name="Additional products",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foods",
                        to="menu.foodcategory",
                        verbose_name="Menu section",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
