[[repos]]
repo = "builtin"
hooks = [
  { id = "check-merge-conflict" },
  { id = "check-toml" },
  { id = "end-of-file-fixer" },
  { id = "trailing-whitespace" },
  { id = "check-added-large-files" }
]

[[repos]]
repo = "https://github.com/tox-dev/pyproject-fmt"
rev = "v2.16.2"
hooks = [
  { id = "pyproject-fmt" }
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.4"
hooks = [
  { id = "ruff-check" },
  { id = "ruff-format" }
]
